### ISSUE TITLE
Sandbox API testing

### ISSUE THREAD

**Issue by newbro** [hubzero/orcid-php#26]
Would it be possible to add a way to override the default host for the api call? Since for testing phase we need to make api call to sandbox.orcid.org

**Comment by spwilson806** [comment]
Yeah, that shouldn't be a problem at all.  It's been some time since I read their documentation.  They use api.orcid.org for their members api and pub.orcid.org for their public api.  Do you know if there is a corollary for testing, or is it all just sandbox.orcid.org?

**Comment by spwilson806** [comment]
Never mind, I found the info that I was looking for (http://members.orcid.org/api/tokens-through-3-legged-oauth-authorization, at the very bottom of the page).

**Comment by newbro** [comment]
If i understand it right, sandbox.orcid.org is just a testing platform for their members api. So I guess adding the follow in Oauth class would suffice:
`public function useSandboxApi()
    {
        $this->level = 'sandbox';
        return $this;
    }`

**Comment by spwilson806** [comment]
Yep, I'll do that.  Thanks!

**Comment by spwilson806** [comment]
This should be resolved in release v0.2, which is now out.  I don't actually have a sandbox account for ORCID, so please let me know if you run into any issues.  The documentation has also been updated to highlight the added functionality. 

As a brief overview, you can now call `useSandboxEnvironment()`.  Note that this is not mutually exclusive to the `usePublicApi()` and `useMemberApi()` methods, as they serve different purposes (i.e. the sandbox environment also has a members and public api).

Hope that helps.  Let me know if you need anything else.
